/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databasep;

import java.sql.SQLException;

/**
 *
 * @author Ma. Belen
 */
public class ConsumoGUI extends javax.swing.JPanel {
    DiaSQL database = new DiaSQL();
    Dia dia = new Dia();
    float cuarto;
    float sala;
    float cocina;
    float agua;
    float luz;
    float total;
    /**
     * Creates new form ConsumoGUI
     */
    public ConsumoGUI() throws SQLException {
        initComponents();
        
        //se accesa a la base de datos
        dia= database.recuperarUltima();
        
        //se obtienen los datos necesarios
        cuarto=dia.getCuarto().floatValue()/25;
        sala=dia.getSala().floatValue()/25;
        cocina=dia.getCocina().floatValue()/25;
        agua=dia.getFlujo().floatValue()/25;
        
        //se muestran los datos registrados
        tfCuarto.setText(Float.toString(cuarto));
        tfSala.setText(Float.toString(sala));
        tfCocina.setText(Float.toString(cocina));
        tfRegadera.setText(Float.toString(agua));
        
        //calculo de gastos
        cuarto= (float) (cuarto*(4.12));
        sala= (float) (sala*(4.12));
        cocina= (float) (cocina*(4.12));
        agua= (float) (agua*(10.11));
        
        //calculo de totales
        luz= cuarto+sala+cocina;
        total=luz+agua;
        
        //Redondeo a 2 decimales
        cuarto= (float) (Math.round(cuarto *100.0)/100.0);
        sala= (float) (Math.round(sala *100.0)/100.0);
        cocina= (float) (Math.round(cocina *100.0)/100.0);
        agua= (float) (Math.round(agua *100.0)/100.0);
        luz= (float) (Math.round(luz *100.0)/100.0);
        total= (float) (Math.round(total *100.0)/100.0);
       
        //Se muestran los gastos
        tfCuarto1.setText(Float.toString(cuarto));
        tfSala1.setText(Float.toString(sala));
        tfCocina1.setText(Float.toString(cocina));
        tfRegadera1.setText(Float.toString(agua));
        
        //Se muestran los totales
        labelSuma.setText(Float.toString(luz));
        labelAgua.setText(Float.toString(agua));
        tfTotal.setText(Float.toString(total));
        
        
    } 
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCuarto7 = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        panelResultados = new javax.swing.JPanel();
        labelCuarto = new javax.swing.JLabel();
        tfCuarto = new javax.swing.JTextField();
        labelSala = new javax.swing.JLabel();
        tfSala = new javax.swing.JTextField();
        labelcocina = new javax.swing.JLabel();
        tfCocina = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfCuarto1 = new javax.swing.JTextField();
        tfSala1 = new javax.swing.JTextField();
        tfCocina1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        labelCuarto8 = new javax.swing.JLabel();
        labelCuarto9 = new javax.swing.JLabel();
        labelCuarto10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelRegadera = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfRegadera = new javax.swing.JTextField();
        tfRegadera1 = new javax.swing.JTextField();
        labelCuarto11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelAgua = new javax.swing.JLabel();
        labelSuma = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        labelCuarto5 = new javax.swing.JLabel();
        labelCuarto6 = new javax.swing.JLabel();
        labelCuarto1 = new javax.swing.JLabel();
        labelCuarto2 = new javax.swing.JLabel();

        labelCuarto7.setText("Q.");

        labelTitulo.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        labelTitulo.setText("CONSUMOS DEL DÍA");

        panelResultados.setBorder(javax.swing.BorderFactory.createTitledBorder("Luz"));

        labelCuarto.setText("Cuarto");

        tfCuarto.setEditable(false);
        tfCuarto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCuartoActionPerformed(evt);
            }
        });

        labelSala.setText("Sala");

        tfSala.setEditable(false);
        tfSala.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSalaActionPerformed(evt);
            }
        });

        labelcocina.setText("Cocina");

        tfCocina.setEditable(false);
        tfCocina.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("kW/h");

        tfCuarto1.setEditable(false);
        tfCuarto1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCuarto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCuarto1ActionPerformed(evt);
            }
        });

        tfSala1.setEditable(false);
        tfSala1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSala1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSala1ActionPerformed(evt);
            }
        });

        tfCocina1.setEditable(false);
        tfCocina1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setText("Gasto");

        labelCuarto8.setText("Q.");

        labelCuarto9.setText("Q.");

        labelCuarto10.setText("Q.");

        javax.swing.GroupLayout panelResultadosLayout = new javax.swing.GroupLayout(panelResultados);
        panelResultados.setLayout(panelResultadosLayout);
        panelResultadosLayout.setHorizontalGroup(
            panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadosLayout.createSequentialGroup()
                .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResultadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelResultadosLayout.createSequentialGroup()
                                .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelResultadosLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(labelSala))
                                    .addComponent(labelcocina))
                                .addGap(18, 18, 18)
                                .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfSala, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelResultadosLayout.createSequentialGroup()
                                .addComponent(labelCuarto)
                                .addGap(18, 18, 18)
                                .addComponent(tfCuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResultadosLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)))
                .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResultadosLayout.createSequentialGroup()
                        .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelResultadosLayout.createSequentialGroup()
                                .addComponent(labelCuarto9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfSala1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfCuarto1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelResultadosLayout.createSequentialGroup()
                                .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelCuarto10)
                                    .addComponent(labelCuarto8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCocina1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResultadosLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(66, 66, 66))))
        );
        panelResultadosLayout.setVerticalGroup(
            panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResultadosLayout.createSequentialGroup()
                        .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCuarto)
                            .addComponent(tfCuarto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSala)
                            .addComponent(tfSala1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCuarto9))
                        .addGap(9, 9, 9)
                        .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfCocina1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelCuarto8))
                            .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelcocina)
                                .addComponent(tfCocina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(labelCuarto10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Agua"));

        labelRegadera.setText("Metros cúbicos");

        jLabel4.setText("Gasto");

        tfRegadera.setEditable(false);
        tfRegadera.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfRegadera1.setEditable(false);
        tfRegadera1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        labelCuarto11.setText("Q.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(labelRegadera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(46, 46, 46))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(tfRegadera, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelCuarto11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfRegadera1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRegadera)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRegadera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRegadera1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCuarto11))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Total"));

        labelAgua.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelAgua.setText("totalAgua");

        labelSuma.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelSuma.setText("totalLuz");

        tfTotal.setEditable(false);
        tfTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        labelCuarto5.setText("+");

        labelCuarto6.setText("Q.");

        labelCuarto1.setText("Luz");

        labelCuarto2.setText("Agua");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCuarto1)
                    .addComponent(labelCuarto2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelSuma)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelCuarto5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelAgua)))
                        .addGap(67, 67, 67))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelCuarto6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCuarto1)
                    .addComponent(labelSuma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCuarto2)
                    .addComponent(labelAgua)
                    .addComponent(labelCuarto5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCuarto6)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitulo)
                            .addComponent(panelResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfCuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCuartoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCuartoActionPerformed

    private void tfSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSalaActionPerformed

    private void tfCuarto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCuarto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCuarto1ActionPerformed

    private void tfSala1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSala1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSala1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelAgua;
    private javax.swing.JLabel labelCuarto;
    private javax.swing.JLabel labelCuarto1;
    private javax.swing.JLabel labelCuarto10;
    private javax.swing.JLabel labelCuarto11;
    private javax.swing.JLabel labelCuarto2;
    private javax.swing.JLabel labelCuarto5;
    private javax.swing.JLabel labelCuarto6;
    private javax.swing.JLabel labelCuarto7;
    private javax.swing.JLabel labelCuarto8;
    private javax.swing.JLabel labelCuarto9;
    private javax.swing.JLabel labelRegadera;
    private javax.swing.JLabel labelSala;
    private javax.swing.JLabel labelSuma;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelcocina;
    private javax.swing.JPanel panelResultados;
    private javax.swing.JTextField tfCocina;
    private javax.swing.JTextField tfCocina1;
    private javax.swing.JTextField tfCuarto;
    private javax.swing.JTextField tfCuarto1;
    private javax.swing.JTextField tfRegadera;
    private javax.swing.JTextField tfRegadera1;
    private javax.swing.JTextField tfSala;
    private javax.swing.JTextField tfSala1;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
}
